General:
  Messages:
    Badge: '&3&l[&2Treebo Tickets&3&l]&r'
Connections:
  Discord:
    WebHooks:
      TICKET:
        Avatar: "http://tickets.treebomc.com/assets/ticket1.png"
        URL: https://discord.com/api/webhooks/???
      IDEA:
        Avatar: "http://tickets.treebomc.com/assets/thinking.png"
        URL: https://discord.com/api/webhooks/???
      REVIEW:
        Avatar: "http://tickets.treebomc.com/assets/hammer.png"
        URL: https://discord.com/api/webhooks/???
      OTHER:
        Avatar: "http://tickets.treebomc.com/assets/ticket1.png"
        URL: https://discord.com/api/webhooks/???
CustomHeads:
  Discord:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: PLAYER_HEAD
    meta:
      ==: ItemMeta
      meta-type: SKULL
      display-name: Re-send to Discord
      lore:
        - '1554'
        - other
        - ShakeforProtein
        - Changes to internal names mean custom enchant lore does not transfer to item
          from token Slit my fucking wrists
        - Survival
      internal: H4sIAAAAAAAAAE2PTU6DQBzF/xpNKnoHrwAWMF24aFpCIZ3BwvC5a2EaPmbahkJluurOG5h4D0/jwht4B2fp4iXv5ffe4ikACjwETc/Ya7vfVowqoEh3oG1X0eMdjDo6dH1LjwoAXI3gNlqznsIXFa6aJaVaJC7LhWPKTAKVeU59eHZ2kdjMHNPhki+m5lJM/nWNbh0bLB27ZbZb9Rseqcuxz+jC13IentJ4paMzrjCxNFynUuETJiX3yHRAsc+8ea5jOzSQjQbZNVJuadkcndG54J6N3nDdCERwlXKfZaTR5V4g4U62ifoCcA/XTiGP3Dy+f34HhXX5+JnFl/2vRH+pM7KQCgEAAA==